services:
  - type: web
    name: stock-trading-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: SUPABASE_URL
        fromDatabase:
          name: supabase
          property: connectionString
      - key: SUPABASE_KEY
        fromDatabase:
          name: supabase
          property: password
    healthCheckPath: /
    autoDeploy: true 